// <auto-generated />
using System;
using Analise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Tab.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20260305180813_CriarPost1")]
    partial class CriarPost1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analise.Models.AgenciaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Debito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Representante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("Analise.Models.AlunoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Mae")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("Nascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Pai")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Analise.Models.AulaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Adjunto1")
                        .HasColumnType("integer");

                    b.Property<int?>("Adjunto2")
                        .HasColumnType("integer");

                    b.Property<int?>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<int>("Cadastro1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Cadastro2Id")
                        .HasColumnType("integer");

                    b.Property<int>("CadastroId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LicaoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Presenca")
                        .HasColumnType("numeric");

                    b.Property<int?>("Professor")
                        .HasColumnType("integer");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("Cadastro1Id");

                    b.HasIndex("Cadastro2Id");

                    b.HasIndex("CadastroId");

                    b.HasIndex("LicaoId");

                    b.HasIndex("TurmaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("Analise.Models.CadastroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .HasColumnType("text");

                    b.Property<string>("Contacto")
                        .HasColumnType("text");

                    b.Property<string>("Contribuinte")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .HasColumnType("text");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Nascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Obreiro")
                        .HasColumnType("text");

                    b.Property<string>("Professor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("Analise.Models.CanalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataActualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nib")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Canais");
                });

            modelBuilder.Entity("Analise.Models.CargoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("cargos");
                });

            modelBuilder.Entity("Analise.Models.ClienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataActualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetalhePep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Limite")
                        .HasColumnType("numeric");

                    b.Property<string>("NIB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nascimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nuit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prazo")
                        .HasColumnType("numeric");

                    b.Property<string>("Registo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Analise.Models.ContaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Debito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("Analise.Models.ContasCobrarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<int?>("CadastroId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Pago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CadastroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CobrarContas");
                });

            modelBuilder.Entity("Analise.Models.ContasPagarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<int?>("CadastroId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Pago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CadastroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PagarContas");
                });

            modelBuilder.Entity("Analise.Models.EntradaEventoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CadastroId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("EventoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EntradaEventos");
                });

            modelBuilder.Entity("Analise.Models.EntradaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<int>("CadastroId")
                        .HasColumnType("integer");

                    b.Property<int>("ContaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LinhaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEntradaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CadastroId");

                    b.HasIndex("ContaId");

                    b.HasIndex("LinhaId");

                    b.HasIndex("TipoEntradaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Analise.Models.EstadoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("estados");
                });

            modelBuilder.Entity("Analise.Models.EventoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Analise.Models.ExtratoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<int?>("CanalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Debito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LinhaId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CanalId");

                    b.HasIndex("LinhaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Extratos");
                });

            modelBuilder.Entity("Analise.Models.FechoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BCI1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BCI2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Caixa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cobranca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Construcao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Corrente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Fevereiro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Inventario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Maguaza")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mahubo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Malhampsene")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Maluana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Manhica")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Maputo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mpesa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Passivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Romao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Fechos");
                });

            modelBuilder.Entity("Analise.Models.InventarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AnoAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TabernaculoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorActual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("Analise.Models.LicaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Licaos");
                });

            modelBuilder.Entity("Analise.Models.LinhaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Debito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Linhas");
                });

            modelBuilder.Entity("Analise.Models.ListaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<string>("Classificacao")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Falta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Presenca")
                        .HasColumnType("numeric");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TurmaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Listas");
                });

            modelBuilder.Entity("Analise.Models.ParticipanteEventoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CadastroId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("EventoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Pago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ParticipanteEventos");
                });

            modelBuilder.Entity("Analise.Models.RecebimentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataActualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recebimentos");
                });

            modelBuilder.Entity("Analise.Models.SaidaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<int>("CadastroId")
                        .HasColumnType("integer");

                    b.Property<int>("ContaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataReferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LinhaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoDespesaId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoServicoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CadastroId");

                    b.HasIndex("ContaId");

                    b.HasIndex("LinhaId");

                    b.HasIndex("TipoDespesaId");

                    b.HasIndex("TipoServicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Saidas");
                });

            modelBuilder.Entity("Analise.Models.TicketModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Problema")
                        .HasColumnType("text");

                    b.Property<string>("Solucao")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Analise.Models.TipoDespesaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoDespesas");
                });

            modelBuilder.Entity("Analise.Models.TipoEntradaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoEntradas");
                });

            modelBuilder.Entity("Analise.Models.TipoSaidaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoSaidas");
                });

            modelBuilder.Entity("Analise.Models.TipoServicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoServicos");
                });

            modelBuilder.Entity("Analise.Models.TurmaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<int>("Cadastro1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Cadastro2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Cadastro3Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("Professor1")
                        .HasColumnType("integer");

                    b.Property<int?>("Professor2")
                        .HasColumnType("integer");

                    b.Property<int?>("Professor3")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("Cadastro1Id");

                    b.HasIndex("Cadastro2Id");

                    b.HasIndex("Cadastro3Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Analise.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Administrar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("integer");

                    b.Property<int?>("CargoId")
                        .HasColumnType("integer");

                    b.Property<string>("Criar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DataActualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Editar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Visualizar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CargoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Analise.Models.AlunoModel", b =>
                {
                    b.HasOne("Analise.Models.EstadoModel", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.AulaModel", b =>
                {
                    b.HasOne("Analise.Models.AlunoModel", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId");

                    b.HasOne("Analise.Models.CadastroModel", "Cadastro1")
                        .WithMany()
                        .HasForeignKey("Cadastro1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.CadastroModel", "Cadastro2")
                        .WithMany()
                        .HasForeignKey("Cadastro2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.CadastroModel", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.LicaoModel", "Licao")
                        .WithMany()
                        .HasForeignKey("LicaoId");

                    b.HasOne("Analise.Models.TurmaModel", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Aluno");

                    b.Navigation("Cadastro");

                    b.Navigation("Cadastro1");

                    b.Navigation("Cadastro2");

                    b.Navigation("Licao");

                    b.Navigation("Turma");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.CanalModel", b =>
                {
                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.ClienteModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Agencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.ContasCobrarModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("Analise.Models.CadastroModel", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Agencia");

                    b.Navigation("Cadastro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.ContasPagarModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("Analise.Models.CadastroModel", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Agencia");

                    b.Navigation("Cadastro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.EntradaEventoModel", b =>
                {
                    b.HasOne("Analise.Models.CadastroModel", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId");

                    b.HasOne("Analise.Models.EventoModel", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Cadastro");

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.EntradaModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.CadastroModel", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.ContaModel", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.LinhaModel", "Linha")
                        .WithMany()
                        .HasForeignKey("LinhaId");

                    b.HasOne("Analise.Models.TipoEntradaModel", "TipoEntrada")
                        .WithMany()
                        .HasForeignKey("TipoEntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Cadastro");

                    b.Navigation("Conta");

                    b.Navigation("Linha");

                    b.Navigation("TipoEntrada");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.ExtratoModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("Analise.Models.ContaModel", "Canal")
                        .WithMany()
                        .HasForeignKey("CanalId");

                    b.HasOne("Analise.Models.LinhaModel", "Linha")
                        .WithMany()
                        .HasForeignKey("LinhaId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Agencia");

                    b.Navigation("Canal");

                    b.Navigation("Linha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.FechoModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("Analise.Models.EstadoModel", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Agencia");

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.InventarioModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Agencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.LicaoModel", b =>
                {
                    b.HasOne("Analise.Models.TurmaModel", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Turma");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.ListaModel", b =>
                {
                    b.HasOne("Analise.Models.AlunoModel", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId");

                    b.HasOne("Analise.Models.EstadoModel", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("Analise.Models.TurmaModel", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Aluno");

                    b.Navigation("Estado");

                    b.Navigation("Turma");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.ParticipanteEventoModel", b =>
                {
                    b.HasOne("Analise.Models.CadastroModel", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId");

                    b.HasOne("Analise.Models.EventoModel", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Cadastro");

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.RecebimentoModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("Analise.Models.ClienteModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Agencia");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.SaidaModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.CadastroModel", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.ContaModel", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.LinhaModel", "Linha")
                        .WithMany()
                        .HasForeignKey("LinhaId");

                    b.HasOne("Analise.Models.TipoDespesaModel", "TipoDespesa")
                        .WithMany()
                        .HasForeignKey("TipoDespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.TipoServicoModel", "TipoServico")
                        .WithMany()
                        .HasForeignKey("TipoServicoId");

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Cadastro");

                    b.Navigation("Conta");

                    b.Navigation("Linha");

                    b.Navigation("TipoDespesa");

                    b.Navigation("TipoServico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.TurmaModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("Analise.Models.CadastroModel", "Cadastro1")
                        .WithMany()
                        .HasForeignKey("Cadastro1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.CadastroModel", "Cadastro2")
                        .WithMany()
                        .HasForeignKey("Cadastro2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.CadastroModel", "Cadastro3")
                        .WithMany()
                        .HasForeignKey("Cadastro3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Analise.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Agencia");

                    b.Navigation("Cadastro1");

                    b.Navigation("Cadastro2");

                    b.Navigation("Cadastro3");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Analise.Models.UsuarioModel", b =>
                {
                    b.HasOne("Analise.Models.AgenciaModel", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("Analise.Models.CargoModel", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId");

                    b.Navigation("Agencia");

                    b.Navigation("Cargo");
                });
#pragma warning restore 612, 618
        }
    }
}
